
server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zzk?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: my_secret
  expiration: 60*60*24*7
  token-name: token